spring.application.name=individuell-labb-2k5-robin

# Betyder att Spring laser miljovariablen APP_API_KEY, och om den inte finns anvands "default-local-key" lokalt
app.api.key=${APP_API_KEY:default-local-key}
